### ISSUE TITLE
Incompatibilities with Python 3

### ISSUE THREAD

**Issue by cclauss** [leitbogioro/SSR.Go#10]
485 days until Python 2 end of life: https://pythonclock.org

[flake8](http://flake8.pycqa.org) testing of https://github.com/leitbogioro/SSR.Go on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./changeport.py:11:13: F821 undefined name 'raw_input'
ifgenport = raw_input()
            ^
./changeport.py:17:17: F821 undefined name 'raw_input'
    ifgenport = raw_input()
                ^
./changeport.py:25:15: F821 undefined name 'raw_input'
    newport = raw_input()
              ^
./changeport.py:30:19: F821 undefined name 'raw_input'
        newport = raw_input()
                  ^
./readjson.py:6:12: F821 undefined name 'file'
jsonfile = file("/etc/shadowsocks.json")
           ^
./changeobfs.py:53:26: E999 TabError: inconsistent use of tabs and spaces in indentation
	print("请按 1 到 10 之间的数字！")
                         ^
./changemethod.py:39:30: E999 TabError: inconsistent use of tabs and spaces in indentation
	writejson.WriteMethod("none")
                             ^
./ssrextra.py:12:20: E999 SyntaxError: invalid syntax
    print subprocess.call(setShell, shell=True)
                   ^
./changepwd.py:22:17: E999 TabError: inconsistent use of tabs and spaces in indentation
	print ("密码不可为空")
                ^
./writejson.py:6:12: F821 undefined name 'file'
jsonfile = file("/etc/shadowsocks.json")
           ^
./writejson.py:12:18: F821 undefined name 'file'
    openjsonfile=file("/etc/shadowsocks.json","w+") # file方法用于打开文件，w+参数表示可读写
                 ^
./changeprotocol.py:36:121: E999 TabError: inconsistent use of tabs and spaces in indentation
	Whether("该协议来自原生shadowsocks协议，已无法适用于审查严密的环境，是否要选择？(y/n)", "y", "n", writejson.WriteProtocol, "协议", "origin", "���议选择", cp)
                                                                                                                        ^
5     E999 TabError: inconsistent use of tabs and spaces in indentation
7     F821 undefined name 'raw_input'
12
```

**Comment by leitbogioro** [comment]
Because of most of Linux's default environment is python 3, so I haven't any plan to compatible with Python 3

**Comment by cclauss** [comment]
You are correct that most Linux distros now default to Python 3 with [__400+ distros shipping Python >= 3.4__](https://github.com/Mariatta/python_versions_and_distros).  This includes the current releases of [Ubuntu](https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes#Other_base_system_changes_since_16.04_LTS), Fedora, Debian, etc. which all default to Python 3, not Python 2.  While I understand and agree with the first part of your sentence above, I do not understand the logic behind the second half.

**Comment by 213wasabi** [comment]
大佬您好。我是小白……
弱弱的问下 怎么在xshell里卸载 这个。。找了半天也没找到

cclauss <notifications@github.com>于2018年9月4日 周二06:30写道：

**Comment by leitbogioro** [comment]
@cclauss Sorry, I made some mistakes in my expression.

I mean that most of Linux's default environment has pre-installed python2 and python3 simultaneously, but some editions such as Cent OS 6/7 ——an important linux distribution only pre-installed python2.

I need to compatible with which only default installed python2 and if change to python3, Cent OS series linux distribution have to compile install python3 for adaptation to work SSR.Go correct, It will consume a numerous time to install.

For example, I want to give up to compatible with Cent OS 6 originally because generate shadowsocksR-URL-QRCode function relies two python pip third part component——pillow and qrcode. one of them, pillow, need at least python 2.7 and can't be installed in python 2.6. I just tried it and it works, to upgrade python 2.6 to python 2.7 spend me a lot of energy.

As you pointed, when I doubt if try to compatible different platform, a lot of scruple works have to proper solved.

Migrate to a new platform benifits a lot especially to developers, But for users, the advantages cannot be certained because users may run kinds of platforms, I just want to gain a suitable balance between development, users who in former or new platform and wish to take care of them as much as possible.

Thanks to your advice again and I will still consider it cautiously.

**Comment by yihozhang** [comment]
I think if an application is no longer maintained, it should not be considered for use, both for safety and maintainability. This is not about benefits for users or benefits for developers, it's just a principle.

Yet we may see in industry, especially in finance, most projects may stick to an old and stable version, this is due to the cost of migration and unexpected conditions. Still, many projects are gradually to embrace new versions. Currently, Python 2 projexts seem to be less and less.

Also, Python 3 is a trend hardly to be reversed. In seeable future, Python 3 will take the place of Python 2. Also from users' perspective, it seems to be hard in 2018 to work with Python without installing Python 3 and installing Python 3 for systems having Python 2 as its default has few pain.

Based on these reason, I can't see a reason not using Python 3 except the costs of migration.

**Comment by yihozhang** [comment]
Also, it seems compatibility with both Python 2 and Python 3 is viable. Please refer to https://github.com/7sDream/zhihu-oauth .

**Comment by LiuChangFreeman** [comment]
We can work together to make the code run with both py2 and py3. Especially with the help of PyCharm, using the function that checks out which part is only capable of py2 and you can update it in the style which the code can run under any python interpreter.

**Comment by cclauss** [comment]
Agreed.  I was not recommending abandoning Python 2 compatibility.  I was recommending working to get to a single codebase that can run in either Python 2 or Python 3.
